package Model.Enums;

public enum SkillType {
    BANESKILL, BARGAINSKILL, BINDWOUNDSSKILL, BOONSKILL, BRAWLSKILL, CREEPSKILL, ENCHANTMENTSKILL, OBSERVATIONSKILL,
    ONEHANDEDWEAPONSKILL, PICKPOCKETSKILL, RANGEDWEAPONSKILL, REMOVETRAPSKILL, TWOHANDEDWEAPONSKILL, STAFFSKILL,
    MOVEUP, MOVEUPRIGHT, MOVEDOWNRIGHT, MOVEDOWN, MOVEDOWNLEFT, MOVEUPLEFT, TALK,

    CAMERAUP, CAMERALEFT, CAMERADOWN, CAMERARIGHT, TOGGLECAMERA;
}
