package Model.Enums;

public enum SkillType {
    BANESKILL, BARGAINSKILL, BINDWOUNDSSKILL, BOONSKILL, BRAWLSKILL, CREEPSKILL, ENCHANTMENTSKILL, OBSERVATIONSKILL,
    ONEHANDEDWEAPONSKILL, PICKPOCKETSKILL, RANGEDWEAPONSKILL, REMOVETRAPSKILL, TWOHANDEDWEAPONSKILL, STAFFSKILL;
}
